### ISSUE TITLE
sudo apt update 

### ISSUE THREAD

**Issue by Exochos** [Titane73/it115-a5-group2-stackproject#13]
run **sudo apt update** on your gcloud instance.
document with screenshots on project document.

**Comment by Aljanabi-ab** [comment]
![21](https://user-images.githubusercontent.com/72470483/101583358-6553fc00-39ec-11eb-96ca-57a57b83f24b.PNG)
![22](https://user-images.githubusercontent.com/72470483/101583582-d693af00-39ec-11eb-8bba-597da1b45aa1.PNG)
